name: mr_checkin
description: "Selfie Attendance App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.3
  fl_chart: ^1.1.1
  table_calendar: ^3.1.1   # âœ… REQUIRED FOR CALENDAR VIEW

  # Storage / Local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0
  path_provider: ^2.1.2

  # Camera & Image & location
  camera: ^0.10.5+5
  image: ^4.1.3
  image_picker: ^1.0.7
  local_auth: ^2.1.8
  geolocator: ^10.1.0
  url_launcher: ^6.2.5

  # Face Detection (ML Kit)
  google_mlkit_face_detection: ^0.10.0

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # PDF / Excel
  pdf: ^3.10.6
  excel: ^4.0.2
  open_filex: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/emojis/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"