name: mr_checkin
description: "Selfie Attendance App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.3
  fl_chart: ^1.1.1
  table_calendar: ^3.1.1

  # Storage / Local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0
  path_provider: ^2.1.2

  # Camera & Image & Location
  camera: ^0.11.3+1
  image: ^4.1.3
  image_picker: ^1.0.7
  local_auth: ^3.0.0
  geolocator: ^14.0.2
  url_launcher: ^6.2.5
  permission_handler: ^12.0.1

  # Face Detection (ML Kit)
  google_mlkit_face_detection: ^0.13.2

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

  # PDF / Excel
  pdf: ^3.10.6
  excel: ^4.0.2
  open_filex: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/emojis/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"